Repository openshift/sriov-tests, pull requests merged in 2020-03, with the labels that each got.

#29 add node selector for the debug pod and increase timeout
  conformance/operator_test.go
  pkg/util/pod/pod.go
Labels: approved, lgtm, size/S

#22 IPv6 sriov connectivity test
  conformance/ipv6.go
  pkg/util/network/network.go
  pkg/util/pod/pod.go
Labels: approved, lgtm, size/L

#27 Test jumbo frames across sriov devices
  conformance/ipv6.go
  conformance/operator_test.go
  conformance/test_suite_test.go
  pkg/util/network/network.go
Labels: approved, lgtm, size/L

#30 Add test for multiple sriov network attachments (25834)
  conformance/ipv6.go
  conformance/operator_test.go
  pkg/util/network/network.go
Labels: approved, lgtm, size/L

#19 Add new test. Verifies that VF is released after pod removal.
  conformance/vfs_assignement_test.go
Labels: approved, lgtm, size/L

#33 Fix vfs assignent
  conformance/vfs_assignement_test.go
Labels: approved, lgtm, size/S

#34 Check for a mellanox card
  conformance/operator_test.go
  pkg/util/cluster/cluster.go
Labels: approved, lgtm, size/M

#35 Change the sriov stable
  conformance/operator_test.go
  conformance/vfs_assignement_test.go
Labels: approved, lgtm, size/M

#37 Change the logic to find the pod's vf index.
  conformance/operator_test.go
  conformance/vfs_assignement_test.go
Labels: approved, lgtm, size/L

#39 Add a check cluster function
  conformance/operator_test.go
  conformance/vfs_assignement_test.go
  pkg/util/cluster/cluster.go
Labels: approved, lgtm, size/M

#41 Use spoof check off for connectivity tests
  conformance/operator_test.go
  conformance/vfs_assignement_test.go
  pkg/util/network/network.go
Labels: approved, lgtm, size/S

#40 Stabilize tests: fix sysfs error, select only supported devices, add a reporter
  conformance/operator_test.go
  conformance/test_suite_test.go
  pkg/k8sreporter/reporter.go
  pkg/util/cluster/cluster.go
  scripts/run-conformance.sh
Labels: approved, lgtm, size/L

#38 Unhealthyvfs
  conformance/operator_test.go
  pkg/util/cluster/cluster.go
  pkg/util/pod/pod.go
Labels: approved, lgtm, size/L

#42 Fix compilation error for wrong parameters.
  conformance/operator_test.go
Labels: approved, lgtm

#43 Make it possible to write the reporter output to a file.
  conformance/test_suite_test.go
  pkg/k8sreporter/reporter.go
Labels: approved, lgtm

#44 Make sure we wait after the cleaning.
  conformance/operator_test.go
  conformance/vfs_assignement_test.go
Labels: approved, lgtm

#45 Flake reduction
  conformance/operator_test.go
  conformance/vfs_assignement_test.go
Labels: approved, lgtm
