Repository openshift/sriov-tests, pull requests merged in 2020-02, with the labels that each got.

#9 Add e2e cases for PF partitioning
  go.mod
  go.sum
  pkg/util/util.go
  tests/e2e/sriovoperatornodepolicy_test.go
  vendor/github.com/intel/sriov-network-device-plugin/pkg/types/types.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/k8s/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/helper.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/sriovnetworknodestate_types.go
  vendor/github.com/openshift/sriov-network-operator/pkg/apis/sriovnetwork/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/L

#10 Enhance the update logic in operator tests
  go.mod
  tests/operator/sriovnetwork_test.go
Labels: size/M

#11 Add OWNERS file for prow integration
  OWNERS
Labels: size/XS

#13 Test partitioning
  conformance/operator_test.go
  pkg/util/cluster/cluster.go
  pkg/util/namespaces/namespaces.go
  vendor/github.com/onsi/gomega/gstruct/elements.go
  vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go
  vendor/github.com/onsi/gomega/gstruct/fields.go
  vendor/github.com/onsi/gomega/gstruct/ignore.go
  vendor/github.com/onsi/gomega/gstruct/keys.go
  vendor/github.com/onsi/gomega/gstruct/pointer.go
  vendor/github.com/onsi/gomega/gstruct/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#16 Add multiple policies test for PF partitioning
  pkg/util/util.go
  tests/e2e/sriovoperatornodepolicy_test.go
Labels: approved, size/L

#15 Add a new test for blocking overlapping range of vfs.
  conformance/operator_test.go
Labels: approved, lgtm, size/M

#14 Fix the FindOneSriovDevice function
  pkg/util/cluster/cluster.go
Labels: approved, lgtm, size/S

#18 Functional tests VF flags
  conformance/operator_test.go
  go.sum
  hack/Dockerfile-utility
  pkg/util/client/clients.go
  pkg/util/namespaces/namespaces.go
  pkg/util/pod/pod.go
  tests/e2e/sriovoperatornodepolicy_test.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#20 Verify that SR-IOV resource injector can inject downward API volume
  conformance/operator_test.go
Labels: approved, lgtm, size/M

#17 Not deploy operator before test suites
  scripts/dummy.yaml
  scripts/run-test.sh
  tests/e2e/e2e_tests_suite_test.go
  tests/operator/operator_tests_suite_test.go
  tests/operator/sriovnetwork_test.go
  tests/operator/sriovoperatorconfig_test.go
Labels: approved, size/M

#23 Fix sriov test for mellanox cards
  conformance/operator_test.go
Labels: approved, lgtm, size/M

#21 Apply labels related to the test plan items.
  conformance/operator_test.go
Labels: approved, lgtm, size/XS

#25 Link state functional test
  conformance/operator_test.go
Labels: approved, lgtm, size/M
